### ISSUE TITLE
Default paths

### ISSUE THREAD

**Issue by kantum** [bonfire-networks/iconify_ex#11]
I spent too much time trying to use this librairy 😄, I finally managed to make the svg configuration work by adding this config:

```elixir
# Configure Iconify
config :iconify_ex, :mode, :img
config :iconify_ex, :generated_icon_static_path, "./priv/static/images/icons"
config :iconify_ex, :generated_icon_static_url, "/images/icons/"
```
It seems like it was made for an older version of Phoenix.

Maybe adding a list of available configuration in the readme would be helpful?

**Comment by mayel** [comment]
Ah is that because the default is in `assets` instead of `priv`?

**Comment by mayel** [comment]
hope this helps: https://github.com/bonfire-networks/iconify_ex/commit/c98d0d546f7c5abacebc77a0b9bf05813e206ff7
