### ISSUE TITLE
Missing step in readme?

### ISSUE THREAD

**Issue by kantum** [bonfire-networks/iconify_ex#12]
I don't know what I'm missing but following the README doesn't work for me.

I had some chance with the svg mode yesterday but now it's not working anymore.

I upgraded Elixir, created a new Phoenix app and followed the README again, still the result is not what I would expect.

```shell
> elixir -v
Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.17.2 (compiled with Erlang/OTP 26)
```

I made a reproduction repository here https://github.com/kantum/iconify_test

The result I get:

<img width="141" alt="image" src="https://github.com/user-attachments/assets/db7c84a1-77d0-4e2a-b42a-b8c4cf988e17">

It seems like the module is not being triggered, no files are generated...

**Comment by mayel** [comment]
Thanks a lot of the repro! I found a bug and also added to readme that you need to include the CSS file to the layout in :css mode. Hope that solves it?

**Comment by kantum** [comment]
It tried again from scratch, it works out of the box now. Thank you!
