### ISSUE TITLE
Dynamic icons

### ISSUE THREAD

**Issue by lobo-tuerto** [bonfire-networks/iconify_ex#14]
Hello :wave: 

I'm trying to use iconify to render (and then update) some dynamic icons.

Initial dynamic rendering is fine, but there seems to be a problem where after an icon has been rendered it will no longer update the component if you change the icon assigned to it.

For example, using this:

```elixir
<.iconify icon={@icon} class={@icon} />
```

Renders all right once.
But, if you change `@icon` to something else after that, it won't update.

First render:

```html
<div data-phx-id="m292-phx-F_9N9rflSOQiqgkE"
  class="heroicons-outline:chat-bubble-left-ellipsis"
  iconify="heroicons-outline:chat-bubble-left-ellipsis"
  aria-hidden="true"></div>
```

After updating `@icon` to `heroicons-outline:envelope`:

```html
<div data-phx-id="m292-phx-F_9N9rflSOQiqgkE"
  class="heroicons-outline:chat-bubble-left-ellipsis"
  iconify="heroicons-outline:envelope"
  aria-hidden="true"></div>
```

As you can see, the `class` attribute is correctly updated.
And if I change the `iconify` attribute from the browser to `heroicons-outline:envelope` it correctly displays the icon I want.

Let me know if you need any more information or want me to test something out.
Thanks! :raised_hands:

**Comment by mayel** [comment]
Hmm first of all you don't need to pass the icon twice, use instead for example `<.iconify icon={@icon} />` or `<.iconify icon={@icon} class="w-6" />`, can you let me know if you still encounter the same issue and I'll have to investigate

**Comment by lobo-tuerto** [comment]
Hey @mayel,

That was just to show that the `class` attribute was indeed changing, but the resulting `iconify` attribute won't update after rendering.

The issue persists, still. :(

**Comment by mayel** [comment]
Found the issue (pretty obvious in hindsight, had to use `assign` everywhere instead of `Map.put`). Please let me know if solved for you on main and I'll release a new version.

**Comment by lobo-tuerto** [comment]
@mayel Just tested it and it solves the issue, thanks! :pray:

**Comment by lobo-tuerto** [comment]
@mayel BTW you left a `debug()` in the code for the commit that solves this issue. :monocle_face:

**Comment by mayel** [comment]
@lobo-tuerto 0.5.4 now realease (and yeah I'm not very diligent about removing those because they're stripped in prod, and this library is pre 1.0...)

**Comment by lobo-tuerto** [comment]
@mayel Yeah, but it's super noisy in dev and gets annoying pretty fast :)

**Comment by mayel** [comment]
yeah fair enough, commented it and added a config to silence any that may slip through in future: `config :untangle, level: :info`

**Comment by lobo-tuerto** [comment]
Thanks, I appreciate it :pray:
