### ISSUE TITLE
Igniter conflict

### ISSUE THREAD

**Issue by kantum** [bonfire-networks/iconify_ex#15]
I came across a bug with igniter installed in production.

I don't know if the problem comes from igniter or iconify_ex, so I just link it here for now: https://github.com/ash-project/igniter/issues/142#issuecomment-2458430758

**Comment by mayel** [comment]
Yeah I gotta agree with @zachdaniel I don't see the link with igniter. You're getting those errors in prod or are you running on fly with dev environment?

**Comment by mayel** [comment]
Because usually all icon downloading happens in dev so this shouldn't appear in prod

**Comment by mayel** [comment]
Yeah based on the code, it looks like you're running with mix rather than a release? If that's what you want to do then you need to follow the same instructions as for dev env in the readme: `cd deps/iconify_ex/assets && yarn && cd -`

**Comment by mayel** [comment]
@kantum could you test if the latest version solves it after you add `config :iconify_ex, :env, config_env()` to your app's config: https://diff.hex.pm/diff/iconify_ex/0.5.5..0.6.0

**Comment by kantum** [comment]
@mayel I have tested, and it works!

I don't understand why it needs to be in the config?
