### ISSUE TITLE
Support phoenix_live_view 1.0

### ISSUE THREAD

**Issue by eriknaslund** [bonfire-networks/iconify_ex#17]
Phoenix Live View 1.0 has just been released, and it'd be great to support it.

I tried it myself, and right now  `surface` (which iconify_ex (optionally) depends on) doesn't support phoenix_live_view 1.0. That issue is being tracked here: https://github.com/surface-ui/surface/issues/760.

Once that's done it'd be great to add a little ` or ~> 1.0` in mix.exs.

**Comment by mayel** [comment]
Good point! Now done in 0.6.1 (FYI it seems Surface is already compatible with LV 1.0)

**Comment by eriknaslund** [comment]
Awesome that it's in 0.6.1, thanks a bunch for the super quick fix @mayel!

Right now the Surface repo (main branch) (https://github.com/surface-ui/surface/blob/main/mix.exs) still says `{:phoenix_live_view, "~> 0.19.0 or ~> 0.20.10"}` for me. Hopefully there are no big issues for them, and they can update it soon.

I didn't notice that the `surface` dependency was optional at first. This makes things a lot easier for me, since I don't use `surface` :)
