### ISSUE TITLE
Floki dependency

### ISSUE THREAD

**Issue by totaltrash** [bonfire-networks/iconify_ex#3]
Floki appears to be needed in the application's :dev environment (while building svg's) https://github.com/bonfire-networks/iconify_ex/blob/main/lib/iconify.ex#L320, but is listed as :test only.

I'm not sure if the best thing would be to make Floki a full dependency in iconify_ex (but then it will get included in the applications prod build?), or advise the user to update their application's mix.exs to use Floki in :dev and :test (a new phoenix app has floki as a dep for :test only).

~Actually, iconify_ex may only need to be a :dev dependency in the application (well, for css and inline at least)? I'll do some testing. Yeah of course it's needed in prod...~

**Comment by yasoob** [comment]
@mayel This is still not fixed. I was getting the same error. I was able to get around it by modifying the floki dependency in my project to look like this:

```
      {:floki, ">= 0.30.0", only: [:dev, :test]},
```

**Comment by mayel** [comment]
@yasoob I've released 0.4.2 with another attempted fix, please let me know if that helps (without having to add the dep to your project)

**Comment by jshekhawat** [comment]
@mayel  This doesn't work with 0.4.2 either. I am using the same fix as yasoob.
