### ISSUE TITLE
`class` attributes erase class when `mode: :css`

### ISSUE THREAD

**Issue by tanguilp** [bonfire-networks/iconify_ex#9]
When mode is set to `:css`, trying to set classes as shown in the doc fails because the default class, that displays the icon, is erased.

It would be nice if these classes would be appended.

**Comment by mayel** [comment]
@tanguilp sorry I missed this issue! I think it may have been fixed in https://github.com/bonfire-networks/iconify_ex/issues/14 
please reopen and let me know otherwise!
